import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navigation from "@/components/navigation";
import { ContentfulLivePreviewProvider } from "@contentful/live-preview/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Finančná Pevnosť",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={inter.className}>
      <ContentfulLivePreviewProvider locale="sk">
        <Navigation background="bg-slate-800" />
        {children}
      </ContentfulLivePreviewProvider>
    </div>
  );
}
